export interface Product {
  id?: string;
  title: string;
  description?: string;
  price: number;
  imageUrl?: string;
  imageData?: Buffer | Uint8Array;
  imageMimeType?: string;
  category?: string;
  brand?: string;
  sku?: string;
  stockQuantity?: number;
  weight?: number;
  dimensionsWidth?: number;
  dimensionsHeight?: number;
  dimensionsDepth?: number;
  color?: string;
  material?: string;
  condition?: string;
  tags?: string;
  shippingCost?: number;
  estimatedShippingDays?: number;
  returnPolicy?: string;
  warranty?: string;
  specifications?: string;
  isDraft?: boolean;
  order?: number;
  createdAt: number;
  updatedAt: number;
}